/*global define*/
define({
    id: "Id",
    requestType: "Tipo Pedido",
    description: "Descripción",
    status: "Estado",
    priority: "Prioridad",
    requestedBy: "Pedido por",
    requestedFinishDate: "Fecha para acabado",
    assignedTo: "Asignado a",
    actualFinishDate: "Fecha actual acabado",
    estimatedUnits: "Unidades estimadas",
    unitType: "Tipo de unidad",
    createdDate: "Fecha de creación",
    save: "Guardar",
    copy: "Copiar",
    updatedDate: "Fecha actualización",
    home: "Casa",
    work: "Trabajo",
    cell: "Portable",
    name: "Nombre",
    first: "Primer",
    last: "Segundo",
    company: "Empresa",
    details: "Detalles",
    mail: "E-mail",
    phone: "Teléfono",
    edit: "Editar",
    cancel: "Cancelar",
    ok: "Aprobar",
    remove: "Borrar",
    request_details: 'Detalles del Pedido'
});