/*global define*/
define({
    root: {
        id: "Id",
        requestType: "Request Type",
        description: "Description",
        status: "Status",
        priority: "Priority",
        requestedBy: "Requested By",
        requestedFinishDate: "Requested Finish Date",
        assignedTo: "Assigned To",
        actualFinishDate: "Actual Finish Date",
        estimatedUnits: "Estimated Units",
        unitType: "Unit Type",
        createdDate: "Created Date",
        save: "Save",
        copy: "Copy",
        duplicate: "Duplicate",
        updatedDate: "Updated Date",
        home: "Home",
        work: "Work",
        cell: "Cell",
        name: "Name",
        first: "Firstname",
        last: "Lastname",
        company: "Company",
        details: "Details",
        mail: "E-mail",
        phone: "Phone",
        edit: "Edit",
        cancel: "Cancel",
        ok: "Ok",
        remove: "Delete",
        request_details: 'Request Details',
        confirm_delete: 'Delete Request?',
        done: 'Done',
        confirm: 'Confirm',
        more: 'More'
    },
    es: true
});